### ISSUE TITLE
does not support 4x20 char lcd

### ISSUE THREAD

**Issue by blacknite** [DzeryCZ/Character-LCD-over-I2C#2]
can you add support for a 4x20 char lcd?  simliar to the raspberry sharp IO library for mono?  

https://github.com/raspberry-sharp/raspberry-sharp-io

**Comment by DzeryCZ** [comment]
Hello,

Thank you for your feedback. This should be already possible.
Constrictor of displayI2C can be overloaded, so you can define it by this code:

```
byte[] llineaddress = new byte[] { 0x00, 0x40 , 0x80 , 0x100 } //here you can define start address of each line.
displayI2C lcd = new displayI2C(DEVICE_I2C_ADDRESS, I2C_CONTROLLER_NAME, RS, RW, EN, D4, D5, D6, D7, BL, llineaddress);
```

If it helps please give a feedback, I'll add this information into README.

**Comment by chrisscph** [comment]
Hi,

I bought this LCD Panel for my project: http://www.amazon.de/SainSmart-Serial-Module-Blacklight-Arduino/dp/B00GHG27Z2/

My Problem is, that the configuration is incorrect. With the standart configuration (displayI2C lcd = new displayI2C(0x27, I2C1, 0, 1, 2, 4, 5, 6, 7, 3); ) I can turn on or off the display light, but I can't write text on the display.

With this configuration on Raspian the LCD Display works: LiquidCrystal_I2C lcd(0x3F, 2, 1, 0, 4, 5, 6, 7, 3, POSITIVE); - when I choose this configuration with 0x3F ... Visual Studio shows an error to runtime.

Chris

**Comment by DzeryCZ** [comment]
Hello,

Many thanks for your feedback. 

Can you be more specific? Please send error message from Visual Studio.

Thank you.

**Comment by DzeryCZ** [comment]
This can help you: https://www.hackster.io/dzerycz/character-lcd-over-i2c-ba8ee9?ref=user&ref_id=14980&offset=0#9845
