### ISSUE TITLE
Support for SSD1306

### ISSUE THREAD

**Issue by JayEnaR** [DzeryCZ/Character-LCD-over-I2C#3]
I was wondering if this would support OLED displays, specifically the 128x32 size ([example](https://www.direnc.net/arduino-nano-128x32-oled-lcd-seti-drkit11-20887-89-B.jpg)).

I would imagine overloading the Constructor to something like this:
`displayI2C lcd = new displayI2C(DEVICE_I2C_ADDRESS, I2C_CONTROLLER_NAME, SCL, SDA);`

Can you tell me if the library can support the aforementioned?

**Comment by DzeryCZ** [comment]
This library is only for character displays not graphical. You'll need another solution for this, sorry.
