### ISSUE TITLE
Not An Issue

### ISSUE THREAD

**Issue by andreweberle** [DzeryCZ/Character-LCD-over-I2C#5]
Hey mate,

Just wondering if you could please point me in the direction of the documentation you used in order to create this interesting library please.

Thanks :)

**Comment by DzeryCZ** [comment]
Hello,

It's quite a long time, I developed it, so I'm not 100% sure. But it must have been datasheets.

- [HD44780](https://www.sparkfun.com/datasheets/LCD/HD44780.pdf)
- [PCF8574](http://www.ti.com/lit/ds/symlink/pcf8574.pdf)

Hope it helps.

**Comment by andreweberle** [comment]
Thanks mate :)
